# Generated by Django 5.2 on 2025-07-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_product_delete_welcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Cart',
            field=models.ManyToManyField(blank=True, related_name='in_cart_of', to='products.product'),
        ),
        migrations.AddField(
            model_name='user',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Products',
            field=models.ManyToManyField(blank=True, related_name='seller_products', to='products.product'),
        ),
        migrations.AddField(
            model_name='user',
            name='Wishlists',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='products.product'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='passwordChanagedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passwordResetCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passwordResetExpiret',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passwordResetVerifed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin')], default='buyer', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='storeDescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='storeName',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
